#ifndef F_TKID_H
#define F_TKID_H

// Token types.
typedef enum {
   // 0
   tk_end,
   tk_hash,    // #
   tk_bracket_l,
   tk_bracket_r,
   tk_paran_l,
   tk_paran_r,
   tk_brace_l,
   tk_brace_r,
   tk_dot,
   tk_increment,
   // 10
   tk_decrement,
   tk_id,
   tk_comma,
   tk_colon,
   tk_semicolon,
   tk_assign,
   tk_assign_add,
   tk_assign_sub,
   tk_assign_mul,
   tk_assign_div,
   // 20
   tk_assign_mod,
   tk_assign_shift_l,
   tk_assign_shift_r,
   tk_assign_bit_and,
   tk_assign_bit_xor,
   tk_assign_bit_or,
   tk_eq,
   tk_neq,
   tk_log_not,
   tk_log_and,
   // 30
   tk_log_or,
   tk_bit_and,
   tk_bit_or,
   tk_bit_xor,
   tk_bit_not,
   tk_lt,
   tk_lte,
   tk_gt,
   tk_gte,
   tk_plus,
   // 40
   tk_minus,
   tk_slash,
   tk_star,
   tk_mod,
   tk_shift_l,
   tk_shift_r,
   tk_question,
   tk_break,
   tk_case,
   tk_const,
   // 50
   tk_continue,
   tk_default,
   tk_do,
   tk_else,
   tk_enum,
   tk_for,
   tk_if,
   tk_int,
   tk_return,
   tk_static,
   // 60
   tk_str,
   tk_struct,
   tk_switch,
   tk_void,
   tk_while,
   tk_bool,
   tk_lit_decimal,
   tk_lit_octal,
   tk_lit_hex,
   tk_lit_binary,
   // 70
   tk_lit_fixed,
   tk_lit_string,
   tk_lit_char,
   tk_paltrans,
   tk_global,
   tk_script,
   tk_until,
   tk_world,
   tk_open,
   tk_respawn,
   tk_death,
   tk_enter,
   tk_pickup,
   tk_blue_return,
   tk_red_return,
   tk_white_return,
   tk_lightning,
   tk_disconnect,
   tk_unloading,
   tk_clientside,
   tk_net,
   tk_restart,
   tk_suspend,
   tk_terminate,
   tk_function,
   tk_special,
} tk_t;

#endif